### ISSUE TITLE
nonpixelmon support

### ISSUE THREAD

**Issue by VanironCZ** [clienthax/SuperModBanner#1]
Hello,
would it be possible to make this mod working without pixelmon on the server? It would be great tool for multiplayer servers but its limited to pixelmon now only which is pity.

**Comment by clienthax** [comment]
We rely on a extra packet in pixelmon, it's easy to spoof the modlist without this

**Comment by VanironCZ** [comment]
So its not possible to make it work without pixelmon api? Players of my server are mostly children unable to spoof modlist.

**Comment by clienthax** [comment]
I can make a version that doesn't rely on pixelmon, but anyone who wants to can circumvent it.
might make it in next few days

**Comment by prodkid** [comment]
This mod is a good replacement http://minecraft.curseforge.com/mc-mods/223332-mod-control

**Comment by VanironCZ** [comment]
@prodkid thank you very much
